<?php

declare(strict_types=1);

function redirect(string $path)
{
    header("Location: ${path}");
    exit;
}

function statement_fetchAll($database, $item)
{
    $query = 'SELECT * FROM ' . $item;

    $statment = $database->query($query);
    return $statment->fetchAll(PDO::FETCH_ASSOC);
}

function date_today(): string
{
    $date_today = new DateTime('NOW');
    $date_today_formated = $date_today->format('Y-m-d');
    return $date_today_formated;
}

function task_completed($list)
{
    if ($list['completed'] == 'yes') {
        return " 💖 completed 💖" . '<br>';
    }
}

function display_task($list, $select_display)
{
    if ($list['user_id'] == $_SESSION['email']) {
        if ($select_display == 'none') {
            echo $list['title'] . ' ' . $list['description'];
            echo task_completed($list);
        } elseif ($list['deadline'] == date_today()) {
            echo $list['title'] . ' ' . $list['description'];
            echo task_completed($list);
        }
    }
}

// FUNCTION TO SEND WELCOME MESSAGE, using PHPMailer and Mailtrap
// To use Mailtrap, create an account on mailtrap.io
// and pick "PHPMailer" to get your credentials to fill in below.

  use PHPMailer\PHPMailer\PHPMailer;
  use PHPMailer\PHPMailer\Exception;

function sendMessage()
{
    require __DIR__ . '/src/Exception.php';
    require __DIR__ . '/src/PHPMailer.php';
    require __DIR__ . '/src/SMTP.php';

    $mail = new PHPMailer();

// FILL IN credentials from Mailtrap here
    $mail->isSMTP();
    $mail->Host = 'smtp.mailtrap.io';
    $mail->SMTPAuth = true;
    $mail->Username = 'hihiufewhfh'; // Paste one generated by Mailtrap
    $mail->Password = 'ohuiowehwig'; // Paste one generated by Mailtrap
    $mail->SMTPSecure = 'tls';
    $mail->Port = 2525;

    $mail->setFrom('info@mailtrap.io', 'Mailtrap');
    $mail->addReplyTo('info@mailtrap.io', 'Mailtrap');
    $mail->addAddress('recipient1@mailtrap.io', 'Susanne');
    $mail->addCC('cc1@example.com', 'Elena');
    $mail->addBCC('bcc1@example.com', 'Alex');

    $mail->isHTML(true);
    $mail->Subject = 'Welcome to Wunderlist!';
    $mail->Body = '<h1> This is the HTML message body <b>in bold!</b> </h1>';
    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';


    if ($mail->send()) {
        echo 'Message has been sent';
    } else {
        echo 'Message could not be sent.';
        echo 'Mailer Error: ' . $mail->ErrorInfo;
    }
}
